### PR TITLE
[MIG] product_configurator_mrp: Migration to 16.0

### PR DESCRIPTION
**Pull request by SirAionTech**
Migration from `14.0` (https://github.com/OCA/product-configurator/tree/c9c57b97070f89cd0eca887a231d27da9ef0d877/product_configurator_mrp).

### CODE REVIEW

**Comment by SirAionTech** [comment]
Rebased after https://github.com/OCA/product-configurator/pull/101#issuecomment-1927270351

**Review by dreispt — APPROVED** [review]

**Comment by SirAionTech** [comment]
Rebased on `16.0`.

**Review by rousseldenis — APPROVED** [review]
LGTM

**Review by Murtaza-SerpentCS — APPROVED** [review]

**Pull request merged**
