### PR TITLE
[14.0][FIX] error configuring a product

### LINKED ISSUE #46: Error during product configuration
From menu item "Products" --> "products". 
On the product template, select "Configure Product" and hit "next". 

FIX: #45 

issue

### PR DESCRIPTION
**Pull request by ReedHayashikawa**
Closes #46

### CODE REVIEW

**Comment by ReedHayashikawa** [comment]
@patrickrwilson

**Review by patrickrwilson — APPROVED** [review]
Tested and works great, no more error. Thanks. LGTM

**Comment by patrickrwilson** [comment]
@dreispt can you review this please?

**Review by dreispt — APPROVED** [review]
LGTM, but since it is not obvious why that code is needed, it would have been nice to add a comment explaining the why

**Comment by dreispt** [comment]
@ReedHayashikawa Please make sire you install precommit checks whenever cloning  a new repo.

**Comment by dreispt** [comment]
@ReedHayashikawa Can you fix precommit errors please?

**Pull request merged**
