### PR TITLE
[16.0][MIG] product_configurator_sale: Migration to 16.0

### PR DESCRIPTION
**Pull request by dannyadair**
requires product_configurator from PR #96

### CODE REVIEW

**Comment by dannyadair** [comment]
There is a bug in that selecting a configurable product in a sales order line hangs, as there is not enough information to pick a variant. The workaround is to click "Configure Product" and select that product template to configure it, which will then add the line in the end.
Picking a configurable product should open the same wizard with that product template already selected.

**Comment by dannyadair** [comment]
This is just waiting on PR #96

**Comment by SirAionTech** [comment]
> This is just waiting on PR #96

Tests are probably failing due to a missing dependency, have a look at https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference(s)-to-another-pull-request(s) to fix them.
Also note that #96 has been superseded by #101.

**Review by SirAionTech — CHANGES_REQUESTED** [review]
Thanks for the PR!
I have tried the module with https://github.com/ursais/product-configurator/pull/3 and it works fine.
I have also looked at the code and suggested some changes in https://github.com/dannyadair/product-configurator/pull/1, please have a look.

I also noticed that the commit of https://github.com/OCA/product-configurator/pull/92 is missing, could you please include it?

Could you please squash bot commits as explained in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests?

For some reason the maintainer @PCatinean has not been tagged in the PR (doing it now), what do you think of this migration?

**Comment by dannyadair** [comment]
@SirAionTech I merged your changes and added test requirements to bring in #101

**Comment by dannyadair** [comment]
@SirAionTech I've now squashed the bot commits

**Comment by dannyadair** [comment]
>I also noticed that the commit of https://github.com/OCA/product-configurator/pull/92 is missing, could you please include it?

I don't actually know how to do that retrospectively but eager to learn!

**Comment by SirAionTech** [comment]
> > I also noticed that the commit of #92 is missing, could you please include it?
> 
> I don't actually know how to do that retrospectively but eager to learn!

If https://github.com/OCA/product-configurator/commit/3061876c997af9f2a1576c42ffca51850208161d impacted only one module, a cherry-pick would have been enough; since this is not the case, I usually do the migration process again.
You can use https://github.com/OCA/odoo-module-migrator and then reuse the commits in this PR as migration commits:
```
# Delete local branch of the PR
git branch -D 16.0-mig-product_configurator_sale
# Migrate the module with all old branches
odoo-module-migrate -i 14.0 -t 16.0 -m product_configurator_sale -fp
# Remove the generated migration commit
git reset --hard HEAD^
# Apply the commits from this PR, from [MIG] onwards
git cherry-pick 0bfb592ed3c5d64d6459e9c76395afbdce290e02^..15a50c1d2ff086a30c97ec97fb016cade92633d9
# Link the generated branch to the branch of the PR, assuming dannyadair is the remote pointing to your fork
git branch --set-upstream-to=dannyadair/16.0-mig-product_configurator_sale
# Check that everything is ok before uncommenting the following because overwrites the PR branch
# git push -f
```
There will be one easy conflict to fix in the cherry-picked [MIG] commit (I just tried it myself) but for the rest this should be it.
Also please note that commits will have to be squashed again.

**Comment by dannyadair** [comment]
@SirAionTech Thank you very much Simone! Sorry for the delay. I've now re-migrated, cherry-picked and then squashed the bot commits.

**Comment by dannyadair** [comment]
Removed test dependency on #101 (merged) and squashed commits.

**Review by dreispt — APPROVED** [review]

**Review by SirAionTech — APPROVED** [review]

**Review by andreampiovesana — APPROVED** [review]
Merge?

**Pull request merged**
