### PR TITLE
14.0 fix context erasement

### PR DESCRIPTION
**Pull request by BenjaHe**
With the old writing, the context is erase instead of being override

### CODE REVIEW

**Comment by BenjaHe** [comment]
Hello @PCatinean,
I change all the .with_context({"key": value}) by .with_context(key=value}) because the method with_context with a dict erase the context instead of override it. This generate bugs in some cases.

I also change a bug "expected_singleton" in the method product_configurator_mrp_component > models > mrp_bom.py > _compute_available_config_components because it break the runboat.

**Review by vanderperre — APPROVED** [review]

**Review by ericchristensen-stretcha — APPROVED** [review]

**Review by andreampiovesana — CHANGES_REQUESTED** [review]
[PR](https://github.com/OCA/product-configurator/pull/95)

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Comment by andreampiovesana** [comment]
merge?

**Pull request merged**
