### PR TITLE
[FIX][14.0] extra price/price computation for configurable products

### PR DESCRIPTION
**Pull request by pledrateam**

### CODE REVIEW

**Comment by PCatinean** [comment]
@DonatasV @gaikaz can you test this MR on your scenario described in https://github.com/OCA/product-configurator/pull/49 ?

**Comment by gaikaz** [comment]
Thank you so much for actually getting back with this! Will definitely test it! Hopefully tomorrow.

**Review by DonatasV — APPROVED** [review]
functional review

**Comment by PCatinean** [comment]
@pledrateam seems code coverage has failed due to the code removal, can we bump it up slightly so all tests are green?

**Comment by DonatasV** [comment]
By testing the scenario described in #49, we also found another bug with is related to `product_configurator_sale` module and the same pricelists... If sale order already has selected pricelist with, for example 50%, discount, then after we use configurator in SO, the price of product will be selected without discount. 
That happening because the price is selected from configurator session but ignores pricelist. (https://github.com/OCA/product-configurator/blob/14.0/product_configurator_sale/wizard/product_configurator.py#L26)

**Comment by PCatinean** [comment]
@DonatasV we should have fixed also the last issue you mentioned. Can you please confirm?

**Comment by DonatasV** [comment]
@PCatinean 
Sorry to keep you wait. I checked and everything work fine now.

**Comment by PCatinean** [comment]
@dreispt is the ocabot maintainer check case sensitive by chance?

**Comment by dreispt** [comment]
@PCatinean  it could be the case, I can fix the maintainers key.

**Comment by dreispt** [comment]
After #54 is merged, you can rebase and try again.

**Pull request merged**
