### PR TITLE
[14.0][FIX] product_configurator: not-stored weight field 

### PR DESCRIPTION
**Pull request by DonatasV**
Correction of bug: original field `weight` is not-stored
Fix issue:  #66

### CODE REVIEW

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Comment by RabbitJon-S73** [comment]
@DonatasV why was that fix closed? Could it be reopened?

**Comment by dreispt** [comment]
A bot closed it out of inactivity.
Merge attempt failed.
Often rebasing the feature branch fixes it.

**Pull request closed without merging**
