### PR TITLE
[16.0][MIG] product_configurator: Migration to 16.0

### PR DESCRIPTION
**Pull request by dannyadair**

### CODE REVIEW

**Comment by pumppi** [comment]
Hi, I tested this with odoo 16. And found out that I got few errors when rendering custom views with OWL and issue was in 

`@property
    def _prefixes(self):
        """Return a dictionary with all dynamic field prefixes used to generate
        fields in the wizard. Any module extending this functionality should
        override this method to add all extra prefixes"""
        return {
            "field_prefix": "__attribute_",
            "custom_field_prefix": "__custom_",
        }`

Changed field prefix and custom prefix to full underscore

**Comment by dannyadair** [comment]
Thanks @pumppi I've applied that change (also to all the tests).

**Comment by matt454357** [comment]
What is preventing this PR from being merged?

**Comment by matt454357** [comment]
@PCatinean, @dreispt, @patrickrwilson,
Can this PR be merged?
I would like to contribute, but waiting on this PR.
Maybe there is still some issue? Not sure why the runboat/build has Pending status.

**Comment by dannyadair** [comment]
Corrected version number to 16.0.1.0.0

**Comment by dannyadair** [comment]
I believe flake8 version should be bumped (latest 6.1.0, and bugbear 23.9.16) but that's outside the scope of this PR.
https://github.com/OCA/product-configurator/blob/16.0/.pre-commit-config.yaml#L122

**Comment by dannyadair** [comment]
@PCatinean @jjscarafia @JordiBForgeFlow @rousseldenis  I think all the precommits could be failing at the moment.
(https://oca.github.io/repo-maintainer-conf/teams.html#product-maintainers)

**Comment by dannyadair** [comment]
Superseded by #101

**Pull request closed without merging**
