### PR TITLE
[14.0][FIX] product_configurator: Product was missing toggle_config method

### LINKED ISSUE #13: product_configurator fails to upgrade after #11 was merged
The `toggle_config` method does not exists in `product.product`.

```
2021-05-17 10:15:25,295 24623 INFO 14-boti-0419 odoo.addons.base.models.ir_ui_view: toggle_config is not a valid action on product.product                                                                                                                                                                                                              View name: product.configurator.form.view.custom.vals
Error context:                                                                                                                                                               view: ir.ui.view(2890,)
 xmlid: product_form_view_custom_vals_inherit
 view.model: product.product
 view.parent: ir.ui.view(429,)
 file: /home/daniel/work14/bot/odoo-boti/src/third-party/product_configurator/views/product_view.xml
```

### PR DESCRIPTION
**Pull request by dreispt**
Closes #13

### CODE REVIEW

**Comment by bizzappdev** [comment]
I doubt this!
as config_ok field belongs to the product.template https://github.com/OCA/product-configurator/blob/14.0/product_configurator/models/product.py#L76

and we have toggle_config already in product_template https://github.com/OCA/product-configurator/blob/14.0/product_configurator/models/product.py#L192

**Comment by dreispt** [comment]
The `product.template` methods are not available in `product.product`, because delegation inheritance only works at field level, not methods.

**Comment by dreispt** [comment]
@bizzappdev Does `-u product_configurator` work for you on current 14.0?

**Comment by bizzappdev** [comment]
YEs 

> @bizzappdev Does `-u product_configurator` work for you on current 14.0?

Yes, It is working properly.

**Comment by bizzappdev** [comment]
> The `product.template` methods are not available in `product.product`, because delegation inheritance only works at field level, not methods.

yes, it can not be delegated True, IMO we do not need the method at the level of the p.p while the field is also from p.t.
and in any case, we need at p.p level then we should just call the product template method and not rewriting it at p.p level

**Comment by dreispt** [comment]
> IMO we do not need the method at the level of the p.p while the field is also from p.t.

It is used in a `product.product` form, so it is needed.
Maybe it should be removed from the form instead?

> and in any case, we need at p.p level then we should just call the product template method and not rewriting it at p.p level

Yes, agree with that,

**Comment by bizzappdev** [comment]
> > IMO we do not need the method at the level of the p.p while the field is also from p.t.
> 
> It is used in a `product.product` form, so it is needed.
> Maybe it should be removed from the form instead?

Yes removing from p.p form view will be an optimal solution. as it is anyhow not needed at that level.

**Comment by dreispt** [comment]
Checked the views, and they look fine!
Undid my change and now it upgraded properly.
Strange, closing.

**Pull request closed without merging**
