### PR TITLE
14.0 [MIG] product configurator base

### PR DESCRIPTION
**Pull request by PCatinean**

### CODE REVIEW

**Comment by dreispt** [comment]
Hello @PCatinean this seems to be duplicating previous effort.
The commit history has already been migrated to v14, hence the merge conflicts.
You will probably work better to apply b757339 on top of current 14.0.

Thanks!

**Comment by dreispt** [comment]
@PCatinean Can make sure pre-commit check passes, please?

**Comment by Chandresh-SerpentCS** [comment]
@PCatinean @dreispt I will take care of pre-commit fixes. I will do it in a new PR using this branch.

**Review by dreispt — APPROVED** [review]

**Pull request merged**
