### PR TITLE
[FIX][14.0] product_configurator_sale order language for sale line name

### PR DESCRIPTION
**Pull request by andreampiovesana**
with_context(lang=self.order_id.partner_id.lang)

### CODE REVIEW

**Comment by andreampiovesana** [comment]
@PCatinean what do you think?

**Comment by andreampiovesana** [comment]
@dreispt what is your opinion?

**Review by dreispt — APPROVED** [review]

**Comment by andreampiovesana** [comment]
merge?

**Review by PCatinean — APPROVED** [review]

**Pull request closed without merging**
