### PR TITLE
[14.0] [MIG] product_configurator_mrp: Migrated the module in v14.

### PR DESCRIPTION
**Pull request by Chandresh-OSI**
Depends on #1

### CODE REVIEW

**Comment by dreispt** [comment]
@Chandresh-OSI Any progress on this?

**Comment by patrickrwilson** [comment]
@Chandresh-OSI I got this green however during testing I'm struggling to figure out an error I was getting before (and still after) I made the lint changes...
In Manufacturing, Click the create button
Walk through configuring a product.
On the last step where it should create the manufacturing order it dislikes the product_qty vs product_uom_qty
image

I'm not 100% sure but it might have to do with this code in the wizard/product_configurator_mrp.py/action_config_done method

        move_finished_lst = []
        move_finished_lst.append(values.get("move_finished_ids")[1])
        values.pop("move_finished_ids")
        values.update({"move_finished_ids": move_finished_lst})

I'm not sure how to proceed as I don't quite understand this section of code.
CC: @dreispt

**Comment by patrickrwilson** [comment]
@Chandresh-OSI @dreispt I was able to fix the above error and the module seems to now be functioning correctly now. 

I'm not sure if my fix is the cleanest way as it's calling multiple on-changes after creation/write instead of trying to include those values in the initial create/write but it seems to work as there is no error and the configured product does get added to the MO and can be reconfigured.

**Comment by max3903** [comment]
Looks good to me. It's only missing the `readme` folder...
https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

**Comment by patrickrwilson** [comment]
> Looks good to me. It's only missing the `readme` folder...
> https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

@max3903 Readme folder has been added. Thanks

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
Sorry, forgot to run it through MergeBot...

**Comment by rousseldenis** [comment]
> Sorry, forgot to run it through MergeBot...

@dreispt could you ask also to have significant commits before merge ?

image

**Pull request merged**
