### PR TITLE
[IMP] product_configurator_mrp(Config Sets Not Working Issue#20)

### PR DESCRIPTION
**Pull request by patrickrwilson**
WIP: Attempt to add config set functionality that was brought up in Issue #20

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@dreispt This PR contains working configuration sets if you could please review. Thanks

**Comment by patrickrwilson** [comment]
@dreispt Travis is now green.

**Review by dreispt — APPROVED** [review]
I wish we can have some tests in a future opportunity.

**Comment by patrickrwilson** [comment]
> I wish we can have some tests in a future opportunity.

Yes, as well as more thorough documentation in the readme. I spent a few hours trying to get tests to work but it became more complicated than expected so even after this merges, I will continue working as time allows to get tests for these.

**Pull request merged**
