### PR TITLE
[16.0][MIG] product_configurator_mrp: Migration to 16.0

### PR DESCRIPTION
**Pull request by matt454357**
Supersedes #102

### CODE REVIEW

**Comment by matt454357** [comment]
The latest push borrows /static/src stuff from  #110 to fix forms and buttons

**Comment by matt454357** [comment]
Hi @Murtaza-OSI, @dreispt
Would one of you be able to take a look at this PR? I believe it is ready to merge.

**Comment by rousseldenis** [comment]
@matt454357 Why not having reviewed #102 instead ? @SirAionTech

**Comment by matt454357** [comment]
> Why not having reviewed #102 instead?

I thought #102 was stale.  I'll make a new PR with a few fixes

**Pull request closed without merging**
