### PR TITLE
FIX Improvement in the definition of prepare_attrs_initial due to the…

### PR DESCRIPTION
**Pull request by jcbr87**
… assignment error before the declaration

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]

**Comment by patrickrwilson** [comment]
@jcbr87 learning how to squash commits will be very useful for your future collaboration. It took me a while to understand it too but basically squashing commits merges commits together to keep things clean so its good practice to squash them when submitting PRs. That way you don't have to go through the approval process again with a new PR.

Here is a good site that teaches you how to squash commits but also just googling it will give you lots of sitest that show you how. https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by jcbr87** [comment]
Hi,
Thanks for the comment, if it seems to me that it is important for the future I will review it. An apology but I thought it would be easier to create it again.
Thanks
________________________________
De: Patrick Wilson ***@***.***>
Enviado: viernes, 21 de mayo de 2021 03:46 p. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Mention ***@***.***>
Asunto: Re: [OCA/product-configurator] FIX Improvement in the definition of prepare_attrs_initial due to the… (#21)


@jcbr87<https://github.com/jcbr87> learning how to squash commits will be very useful for your future collaboration. It took me a while to understand it too but basically squashing commits merges commits together to keep things clean so its good practice to squash them when submitting PRs. That way you don't have to go through the approval process again with a new PR.

Here is a good site that teaches you how to squash commits but also just googling it will give you lots of sitest that show you how. ***@***.***/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by jcbr87** [comment]
Hello,
It takes something more on my part to be able to pass and mix the PR.
Thank you

**Comment by jcbr87** [comment]
How can I validate the codecov checks?

**Pull request closed without merging**
