### PR TITLE
[FIX]Correcting assignment error in the wizard on line 670

### PR DESCRIPTION
**Pull request by jcbr87**

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
@patrickrwilson Is this related to anything you're working on?

**Comment by jcbr87** [comment]
Hello,


I am working on a client implementation, I am using the product configurator.

Saludos Julio
________________________________
De: Daniel Reis ***@***.***>
Enviado: jueves, 20 de mayo de 2021 10:27 a. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Author ***@***.***>
Asunto: Re: [OCA/product-configurator] [FIX]Corrigiendo error de asignacion en el wizard en la linea 670 (#16)


@patrickrwilson<https://github.com/patrickrwilson> Is this related to anything you're working on?

**Comment by patrickrwilson** [comment]
@dreispt yes, I didn't translate this to be the same issue but it seems to be. @jcbr87 has a better fix in this PR than my solution so I will cancel my PR.

**Comment by patrickrwilson** [comment]
@jcbr87 can you add that extra line to the unit tests to make this green? Then I can approve.

**Comment by jcbr87** [comment]
Ok, How do I add it?

Thanks
________________________________
De: Patrick Wilson ***@***.***>
Enviado: jueves, 20 de mayo de 2021 11:04 a. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Mention ***@***.***>
Asunto: Re: [OCA/product-configurator] [FIX]Corrigiendo error de asignacion en el wizard en la linea 670 (#16)


@jcbr87<https://github.com/jcbr87> can you add that extra line to the unit tests to make this green? Then I can approve.

**Comment by dreispt** [comment]
I think it is fine, codecov check won't prevent a merge.
Adding back the tests is a worthy goal, but won't be trivial I'm afraid.

**Comment by patrickrwilson** [comment]
> I think it is fine, codecov check won't prevent a merge.
> Adding back the tests is a worthy goal, but won't be trivial I'm afraid.

Understood, there is a small pre-commit change so after @jcbr87 fixes that then I will approve.

**Comment by rousseldenis** [comment]
Is it possible to modify commits comments as everybody does not speak spanish :smile:

**Review by jcbr87 — COMMENTED** [review]
Correcting assignment error in the wizard on line 670

**Comment by jcbr87** [comment]
Thats ok, the next comments, i make in inglish.

Thanks
________________________________
De: Denis Roussel (ACSONE) ***@***.***>
Enviado: jueves, 20 de mayo de 2021 12:54 p. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Mention ***@***.***>
Asunto: Re: [OCA/product-configurator] [FIX]Corrigiendo error de asignacion en el wizard en la linea 670 (#16)


Is it possible to modify commits comments as everybody does not speak spanish 😄

**Comment by jcbr87** [comment]
Something more is needed from me.

________________________________
De: Denis Roussel (ACSONE) ***@***.***>
Enviado: jueves, 20 de mayo de 2021 12:54 p. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Mention ***@***.***>
Asunto: Re: [OCA/product-configurator] [FIX]Corrigiendo error de asignacion en el wizard en la linea 670 (#16)


Is it possible to modify commits comments as everybody does not speak spanish 😄

**Review by patrickrwilson — APPROVED** [review]

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Comment by jcbr87** [comment]
@patrickrwilson who is merge this pull request?

thanks you
________________________________
De: Patrick Wilson ***@***.***>
Enviado: jueves, 20 de mayo de 2021 03:30 p. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Mention ***@***.***>
Asunto: Re: [OCA/product-configurator] [FIX]Correcting assignment error in the wizard on line 670 (#16)


@patrickrwilson approved this pull request.

LGTM

**Comment by rousseldenis** [comment]
@jcbr87 Could you squash your commits ?

**Comment by jcbr87** [comment]
Sorry, what should I do?
________________________________
De: Denis Roussel (ACSONE) ***@***.***>
Enviado: viernes, 21 de mayo de 2021 01:45 a. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Mention ***@***.***>
Asunto: Re: [OCA/product-configurator] [FIX]Correcting assignment error in the wizard on line 670 (#16)


@jcbr87<https://github.com/jcbr87> Could you squash your commits ?

**Comment by rousseldenis** [comment]
There is no need to have so much commits for a line modification:

image

You need to make 'git rebase -i HEAD~4' and fixup the last 3 commits into the first. And a good commit message for that one too

**Comment by jcbr87** [comment]
I will close the PR and create a new one with the specific change

**Comment by jcbr87** [comment]
Hi,
I have closed the previous PR and created a clean one, with the correct comments.
https://github.com/OCA/product-configurator/pull/21

thanks
________________________________
De: Denis Roussel (ACSONE) ***@***.***>
Enviado: viernes, 21 de mayo de 2021 09:26 a. m.
Para: OCA/product-configurator ***@***.***>
CC: Julio Cesar Bravo Rodríguez ***@***.***>; Mention ***@***.***>
Asunto: Re: [OCA/product-configurator] [FIX]Correcting assignment error in the wizard on line 670 (#16)


There is no need to have so much commits for a line modification:

[image]<https://user-images.githubusercontent.com/19529533/119153012-21f8c180-ba51-11eb-996f-ab1bf3b82306.png>

You need to make 'git rebase -i HEAD~4' and fixup the last 3 commits into the first.

**Pull request closed without merging**
