### PR TITLE
[17.0][MIG] product_configurator: Migration to 17.0

### PR DESCRIPTION
**Pull request by dreispt**
Supersedes #106

### CODE REVIEW

**Comment by simahawk** [comment]
@dreispt hi, what's the status here?

**Comment by dreispt** [comment]
I don't have plans to work on this.
I just fixed commit history so that this is in a good place for people to continue with the migration.
Feel free to take over.

**Comment by simahawk** [comment]
FYI The pandoc*.deb file has been added here. I'm updating the template here https://github.com/OCA/product-configurator/pull/129 and I will cleanup this PR (also removing all the improvements to be in a separated PR if they are not mandatory for 17.0)

**Comment by simahawk** [comment]
BTW I've just found out that most of the tests are not running because they were commented on v13

image

It's the same till 16 https://github.com/OCA/product-configurator/blob/16.0/product_configurator/tests/__init__.py

:scream: :scream: :scream: :scream: :scream: :scream:

**Comment by simahawk** [comment]
FYI I'm cleaning up this branch, splitting things and keeping what is compatible w/ v16 to ease fwd/back porting.
I started here https://github.com/OCA/product-configurator/pull/133
Then I'll move on w/ this mig but I'll split out all the improvements and leave them behind for another PR to ease review and backporting. I'm doing my best to preserve ownership.

**Comment by simahawk** [comment]
https://github.com/OCA/product-configurator/pull/135

**Pull request closed without merging**
