### PR TITLE
[ZAD/0018342] Upgrade Product Configurator to v16

### PR DESCRIPTION
**Pull request by patrycjuszerpm**

### CODE REVIEW

**Comment by theangryangel** [comment]
Hi @patrycjuszerpm. 

Is there any chance you can re-submit using the preferred method identified at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch? Without that I doubt anyone will merge this as-is.

The mako import errors are due to Mako no longer shipping with Odoo out of the box, you'll want to add that the dependencies if you intend to keep it.

The pre-commit failures should be resolved by https://github.com/OCA/product-configurator/commit/e629617e96d5e2ed29357d0c665c4820eb50ba2c

**Comment by patrycjuszerpm** [comment]
I can try resubmitting, however if additional adjustments to the code are required I'd need to discuss it with my supervisor in order to reserve time slot for the job.

**Comment by dannyadair** [comment]
There is now #96 and #97

**Comment by dannyadair** [comment]
@patrycjuszerpm I created #96 and #97 by re-applying your changes "the proper way", and then fixing all linting and test complaints etc.. However, there is still a bug in the UI (hangs when you select a configured product in a sales order). Could you have a look to see what's wrong?

**Pull request closed without merging**
